version: "3.9"

services:
  hs-data-dis-vpn-proxy:
    image: 'nginx:stable-alpine'
    volumes:
      - ./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
  hs-data-dis-app:
    build:
      context: .
      dockerfile: app.Dockerfile
      args:
        uid: ${UID}
    image: hs-data-dis-app:latest
    container_name: hs-data-dis-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html:delegated
      - ./docker-configs/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - 8001:80
  hs-data-dis-mariadb:
    image: mariadb:10.8.3
    container_name: hs-data-dis-mariadb
    command: ['--default-time-zone=+00:00','--default-authentication-plugin=mysql_native_password']
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - hs-data-dis-mariadb-data:/var/lib/mysql
  hs-data-dis-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hs-data-dis-phpmyadmin
    environment:
      - PMA_HOST=hs-data-dis-mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=120M
    ports:
      - "8002:80"
volumes:
  hs-data-dis-mariadb-data:
